### ISSUE TITLE
Pre-fill form based on URL parameters

### ISSUE THREAD

**Issue by hesara** [spring-io/initializr#107]
In tutorials etc., it would be useful to provide a link to start.spring.io with some options already pre-filled.

As opposed to the curl approach where only the listed technologies are used, a link that pre-selects some options and lets the user finish filling in the rest of the fields would help make other options easily discoverable.

**Comment by spilth** [comment]
+1 for this idea.

I'd love to go to `http://start.spring.io/?groupId=io.spring&javaVersion=1.7` and have those things pre-filled/selected and be able to bookmark it. Then I can tweak the rest of the settings as needed.

**Comment by spencergibb** [comment]
:+1: I like this example from gitignore.io https://www.gitignore.io/api/java,intellij,eclipse,python,maven,gradle

Maybe with an option to download directly as well.

That way you can just share a url!

**Comment by sdeleuze** [comment]
I am starting to work on this and will submit a PR.

**Comment by bclozel** [comment]
:-1: vote for me

Here are the few use cases I could think of for this:

1. you're lazy and you want to bookmark your usual preferences (I like gradle and I'm adding devtools no matter what)
1. you're a library developer and you want to promote your Spring Boot starter with a URL pre-selecting your starter
1. you want to copy/paste links to your colleagues to generate projects with all options pre-selected (change the group/artifactId and click generate!)

For use case 1), we could store those preferences on the client (using the browser localStorage). Why not! But this asks new questions, like how should developers manage those preferences?

For use case 3), why not share directly the form link to get the generated project with a single click?

In general, I think that most of those options aim at making things easier for "content producers" to share their opinion easily, instead of saying "go to start.spring.io, select starter X, Y and Z".

But in my opinion this goes against one important goal behind Initializr: trying to provide our opinion and following closely the Spring portfolio. Providing that kind of contract would skew the numbers and make the next big changes in the UI and/or defaults harder.

We've spent a significant amount of time simplifying the UI and I'd rather spend our "complexity budget" on something more meaningful for the users (read: supported by hard evidence in the usage stats).

**Comment by dsyer** [comment]
I don't really have a strong opinion. If it's easy to implement it won't cost much and doesn't seem particularly complex.

**Comment by sdeleuze** [comment]
I have created a simple (but useful I hope) JS based implementation of this functionality that I would like to use for Kotlin support. See PR #173 for more details.

**Comment by bclozel** [comment]
I've just reviewed the PR sent by @sdeleuze - I'm happy with it since:

* the scope is limited scope to client-side only (it's using hashbangs and not request params, only the JS code has been modified)
* as a first step, this feature is not displayed in the public UI but in the README; this allows us to experiment and not break promises if we think this doesn't work out
* I'm fine with `type`, `groupId`, `artifactId`, `name`, `description`, `packageName`, `packaging`, `javaVersion` and `language`, but I'd like to rule out `bootVersion` as this is something that's often and automatically updated. We'd rather like developers to start new projects with the latest, recommended version

**Comment by sdeleuze** [comment]
Good point @bclozel, I have removed `bootVersion` support.

**Comment by snicoll** [comment]
I was about to write the same thing for the bootVersion. Looks like we're on the same page.
