### ISSUE TITLE
Adding external dependency 

### ISSUE THREAD

**Issue by bansmani** [spring-io/initializr#1080]
Hi Team, 
Thanks for providing this API. 
First of all this is not an issue, but a question, couldnt find any IRC channel where I could ask this question. 

We are looking to add 3rd party and our internal dependency directly in our POM or Gradle file while this project starter template it generating, but couldnt find any option,
 can you please help and suggest what can be done?

**Comment by snicoll** [comment]
> First of all this is not an issue, but a question, couldnt find any IRC channel where I could ask this question.

The [contributing page](https://github.com/spring-io/initializr/blob/master/CONTRIBUTING.adoc#using-github-issues) has a section about how to use GitHub issues and the header of the readme has a link to our Gitter channel.

> We are looking to add 3rd party and our internal dependency directly in our POM or Gradle file while this project starter template it generating, but couldnt find any option,

I don't understand what that means. Do you mean adding 3rd party dependency? Have you looked at [the documentation](https://docs.spring.io/initializr/docs/current/reference/html/)? If that doesn't help, let's follow up on Gitter and we can reopen if it turns out something can be improved in the library.
