### ISSUE TITLE
Reimagine the web UI as a shopping cart

### ISSUE THREAD

**Issue by william-tran** [spring-io/initializr#112]
As a developer, I'd like to shop for project dependencies by browsing, filtering by category, searching with terms, adding to cart, hit checkout, and generate a project. 

More metadata like tags, project urls, extended descriptions, etc could be leveraged by this UI. The list of dependencies has grown quite a bit and is getting a bit daunting to go through, and it's not immediately clear how to map my project's needs to the names of dependencies.

**Comment by snicoll** [comment]
I like the idea and agree on the problem of having a large set of dependencies.

We have IDE support now: both STS and Intellij IDEA shows a wizard that allows you to generate a new project using spring initializr. I believe they should be _affected_ by this issue in a similar manner. 

Thoughts @bclozel, @kdvolder, @yanncebron ?

**Comment by YannCebron** [comment]
+1

IntelliJ IDEA already has collapsible categories
maybe a simple "quicksearch" on all available items would be enough in most cases

**Comment by kdvolder** [comment]
I have received feedback on the Eclipse wizard also that the list of dependencies is getting a bit daunting. Some kind of search UI would be probably help. But maybe that doesn't require an extension of the metadata.

Another feedback I've gotten is that people often don't know what each dependency is for and how/when to use it. The Eclipse wizards shows the description of the dependencies in tooltips, but mostly these descriptions aren't very helpful (essentially just slightly longer English sentences repeating the name of the dependencies without conveying much, if any, extra information).

What might be useful, is to make the descriptions more informative, and this would also benefit a 'search UI' as it could search the descriptions as well as just the names.

I wonder if maybe it might be a good idea to include a link to documentation about each dependency that explains details. If the wizard UI could somehow show this information and allow the user to dive into the details by following the link that could be a great way for people to learn about the various goodies spring boot provides.

As it is now, users see a list of names but may not be able to guess if a given dependency is what they need, ot if it is, how they use it once its added to their project.

**Comment by snicoll** [comment]
good stuff, thanks.

I have the feeling (pending @bclozel feedback since he did all the UI) that we may benefit more from some UI arrangements in the IDE with additional meta-data support from the service. Note sure about UI change in the (default) HTML view.

Kris, I agree that the description are not very useful. I don't want to make them too long because theses are shown in command line tools. We could take the same convention that we did in other places of extracting the first sentence for that.

In any case, this is definitely an issue: the use of the `aop` starter is very high in the statistics while it's "only" used to write custom aspects and use AspectJ. I assume that users are confused and think they need to add that to get the "proxy stuff".

I'll give it more thoughts and maybe fork an issue for the documentation if we believe we need to do more here.

**Comment by bclozel** [comment]
Two ways to solve this in my opinion:

1. incrementally improve the current arrangements
1. totally revisit this UI and adopt a new paradigm as the explosion of starters changed the deal

The first choice will probably involve changes in section names, help text when hovering elements, reordering sections, collapsible categories... But we'll keep the "static HTML form" recipe that works with various clients: browsers, IDEs, CLI...

The second choice can lead to interesting ideas like "shopping carts" or step by step wizards powered by decision trees ("Are you building a web app? Yes/no" -> ...). While this solution is quite appealing, solutions would probably lead to massive changes in the metadata format (for the step-by-step wizard) and/or radically different experiences depending on the client you're using (:moneybag: to whoever knows how to do the shopping cart thing with curl).

**Comment by dsyer** [comment]
I also don't like the "shopping cart" analogy much. I want a one-stop, one-click experience, and I hate "wizards". Documentation would go a long way though.

**Comment by willtran-** [comment]
Put yourself in a novice developer's shoes though. The key idea is that they know what their project needs to do, but don't know what Spring supported dependencies they need to get the job done. Where do you start? Read lots of docs and googling... you can spend a lot of time doing that or even get off track. start.spring.io can be that starting point. 

It's the same problem with online shopping experiences. I know what I need, I don't know what products being offered will best suit my needs. That's why I suggested a shopping cart, but it doesn't neede to be taken literally. The essential parts of the experience are, I can search or browse for what I want, and I see a list of suggestions. I can click into things that seem interesting to see details and make sure its the right fit. Links to documentation or samples can be provided in those details.

**Comment by kdvolder** [comment]
Just to throw a potentially odd-ball idea into the mix. It might be useful
to provide the metadata about the various "starter" dependencies
 independently of the initializr service. As a user, I would really like to
be able to easily add dependencies I initially forgot, or which I didn't
even know I would need later as I add more features to my application.

It is a bit odd that I have a fancy UI to pick the initial dependencies but
then after I created my project, I can't access the same information
anymore to update my dependencies.

So I imagine I would like to have similar UI as the wizard has (dialog/view
with similar/same dependency options) to add more dependencies to an
existing boot app.

The IDE could porbably implement this, but to show options that are
consistent with the initial wizard, it would be nice to have an authorative
source of 'starter dependencies metadata' which is independent of the
intializr app. (initializr app and IDE 'update starters' UI can share this
metadata source).

**Comment by dsyer** [comment]
Isn't the initializr service a perfect place to maintain that data? It's open and available and free to all, and it already has a lot of metadata about starters. Adding some more seems like a better idea than creating another indirection.

**Comment by snicoll** [comment]
Yes, Kris and I discussed and it looks like we need to polish a bit what we've started with http://start.spring.io/metadata/service (i.e. rename that to `config` and offer a well-structured version of it with only the dependencies)

**Comment by snicoll** [comment]
I'd argue that what we have right now would fulfil this request, in particular

> maybe a simple "quicksearch" on all available items would be enough in most cases

We can now search on the name, description and keywords. We can improve the description or add keywords if that's missing (let's create individual issue(s) for that). As of the dependencies endpoint, we have that too now, check start.spring.io/dependencies.
