### ISSUE TITLE
ProjectGenerationInvoker is not thread safe

### ISSUE THREAD

**Issue by snicoll** [spring-io/initializr#1124]
See https://github.com/spring-io/start.spring.io/issues/522#issuecomment-686793273

**Comment by mkrzywanski** [comment]
How do we want to approach this? I think the solution would be to synchronize on `temporaryFiles` when computing and removing from it. Using `ConcurrentHashMap` is not an option because although `remove` and `computeIfAbsent` would be thread safe - it is still `Map` of `Lists` so we would have to synchronize access to those `List`s if two or more threads get access to the same key.

**Comment by mkrzywanski** [comment]
Another option would be to change to `ConcurrentHashMap` (it does not preserve the order like `LinkedHashMap` but there is no usage of this feature anyway) and use `compute` instead of `computeIfAbsent`.

**Comment by snicoll** [comment]
Closing in favour of PR #1125
