### ISSUE TITLE
Issue with gradle java 15 projects due to incompatible gradle version

### ISSUE THREAD

**Issue by pstitt** [spring-io/initializr#1162]
We are running a custom initializr using v0.9.2, and it generates Java 13 projects ok with gradle 6.6.1.

However, we updated to support Java 15 and it generates projects with gradle 6.6.1 which is incompatible with Java 15.

Is there a way for us to override the gradle wrapper version in the generated project?.

Or will this require a new initializr version?

**Comment by snicoll** [comment]
Thanks for the report. 

The current arrangement is not ideal. When you opt-in for spring conventions (`initializr-generator-spring`) you're more exposed to have them outdated with recent changes in the ecosystem: an older version of the conventions may not be able to generate projects with more recent version of the ecosystem just like older Spring Boot versions would not be compatible with recent 3rd party libraries. The release schedule of the library is usually behind new major of Spring Boot to give us enough room to work on features.

`0.10.0-SNAPSHOT` does work with Java 15 since we use that in production. If Gradle is the only problem, you could put an updated Gradle wrapper in `src/main/resources/gradle/6` in your own instance. Alternatively, you could have a contributor that runs last and update `gradle-wrapper.properties` to point to another binary. 

I'll flag this issue for team attention as we may want to revisit the release lifecycle of the conventions.

**Comment by pstitt** [comment]
Thanks for the quick response. I've gone with bundling a gradle wrapper in the resources.
