### ISSUE TITLE
Support adding new attribute values to annotations of the MainApplication

### ISSUE THREAD

**Issue by gaston-freire** [spring-io/initializr#1264]
The use case is the following: custom dependency needs an  `exclude = SomeClass.class` attribute added to the `@SpringBootApplication` annotation of the MainApplication. 
Using a `MainApplicationTypeCustomizer<TypeDeclaration>` there is no way to modify the existing annotation.

**Comment by gklp** [comment]
Maybe, you can use SourceCodeProjectGenerationConfiguration.java to do this. It might not be right way but it's working.  @snicoll @gaston-freire 

```java
typeDeclaration.annotate(
	Annotation.name("org.springframework.boot.autoconfigure.SpringBootApplication", builder -> {
		builder.attribute("exclude", Class.class,
				"org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration");
	}));
```

**Comment by filiphr** [comment]
The example proposed by @gklp is something that we want to use. However, it is currently not possible, because the generated code will have 2 `@SpringBootAplication`. With PR #1318, I am trying to resolve this. 

The example will work correctly if the custom `MainTypeApplicatiionCustomizer` has a higher precedence than the default in from the initializr.

The current way to achieve this is to do:

```java
typeDeclaration.annotate(Annotation.name("org.springframework.boot.autoconfigure.EnableAutoConfiguration", builder -> {
        builder.attribute("exclude", Class.class, "org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration");
}));
```

However, IntelliJ is showing a warning / error because the `@EnableAutoConfiguration` is redundant in this case.

**Comment by snicoll** [comment]
This issue is now superseded by #1424. When merged, you can achieve the above with the following code.

```java
typeDeclaration.annotations().add(ClassName.of("org.springframework.boot.autoconfigure.SpringBootApplication"), builder -> builder.add("exclude",
		ClassName.of("org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration")));
```
