### ISSUE TITLE
Handle Unicode character in project generation

### ISSUE THREAD

**Issue by snicoll** [spring-io/initializr#1328]
See https://github.com/spring-io/start.spring.io/issues/990

I don't know how easy it would be to map the characters to something that would work but it's certainly worth researching. Or we could chose to fail upfront, rather than failing later as we do now.

**Comment by wilkinsona** [comment]
The `Normaliser`-based technique described in https://www.baeldung.com/java-remove-accents-from-text could help here.

**Comment by okan35** [comment]
Hello, if noone is working on this I could take it as a first timer contribution.

**Comment by snicoll** [comment]
The issue is yours @okan35. Thank you very much and let us know if you have any question.

**Comment by okan35** [comment]
Hello, so basically I am trying to run the initializr-generator just so that at least I can the api for generation but I haven't been successful.

What I have tried so far is doing  `./mvnw clean install` and then in initializr-generator/target directory do `java -jar initializr-generator-0.13.0-SNAPSHOT.jar` but this always gives me `no main manifest attribute, in C:/Users/pc/Desktop/okan/spring initializr/initializr/initializr-generator/target/initializr-generator-0.13.0-SNAPSHOT.jar
`
Do you have any suggestions regarding how I can get generator to work as I have also added just the generator in a new project like it is said in documentation but that also hasn't been successful.

So I just need to be able make it work basically, what would you suggest regarding this ?

**Comment by snicoll** [comment]
@okan35 thanks for the feedback. There are a number of tests in `initializr-web`, including HTTP-based tests that you can improve to validate that unicode characters are handled properly. `initializr-generator` is a "simple" java library, not an app.

If you want to play around with curl against the service, you can give `initializr-service-sample` in this repository a try maybe?

**Comment by okan35** [comment]
So basically I should not be providing a fix but just add an additional test in `initializr-web` ?

**Comment by nirbhay24** [comment]
@snicoll I have added a commit, with Idea that we should sanitize input, and convert accents character to normal char.
And have raised a PR for same let me know if it looks fine.

**Comment by snicoll** [comment]
Closing in favor of PR #1345
