### ISSUE TITLE
Make pom file follow the Convention.

### ISSUE THREAD

**Issue by chenrujun** [spring-io/initializr#1329]
## Context

1. Link to pom code convention: https://maven.apache.org/developers/conventions/code.html#pom-code-convention
2. The initializer generated didn't follow above convention. For example: the order of   `</dependencies>`
  `<dependencyManagement>`.
![image](https://user-images.githubusercontent.com/13167207/190580925-8f41df0b-7bdb-483c-ae37-ed9527082ed1.png)
![image](https://user-images.githubusercontent.com/13167207/190581013-8f4038f2-00b8-47b4-94a2-dd5f1098f3ee.png)

## Goal
Make the generated pom follow pom code convention. Not only the `</dependencies>` and `<dependencyManagement>`, need to check all items.

**Comment by wilkinsona** [comment]
Thanks for the suggestion. Spring Initializr and start.spring.io are, in large part, about the team's opinions. It's my opinion that the ordering of the poms as currently generated is better than the ordering that the Maven team recommends. I think it's also interesting to consider that Maven's own poms don't follow the documented convention. Consider [this pom](https://github.com/apache/maven/blob/47e2d689d687358a85c2cdecc176cac36093817e/pom.xml), for example. It has `properties` before `modules` but the convention is for `properties` to appear after `distributionManagement`. There are other differences too.

When I'm reading or editing a pom file, it's most often to work with the dependencies or a property. I find it useful having the parent and the module's coordinates first to provide some context. I then prefer the properties and dependencies to come next so they're easy to find without searching/scrolling. Following the documented conventions results in the dependencies and properties getting a bit lost in the middle of the pom.

One change that I do think may be worth making is just reversing the order of `<dependencies>` and `<dependencyManagement>` so that the dependency management (which provides information about dependency versions) comes before the dependency declarations.

Let's see what the rest of the team thinks.

**Comment by snicoll** [comment]
I would put dependencies and plugins first with dependency management and plugin management after, respectively. It is a bit specific to our own use of it but any version we set in `dependencyManagement` is covered by a `.version` property at the top of the file. 

I personally (strongly) prefer to see what the project actually uses (the dependencies) rather than the details of how the version(s) for such dependencies are resolved (the dependencies management).

**Comment by wilkinsona** [comment]
Given that we've already got 3 or 4 different opinions in this thread, I think we should close this issue. I doubt we'll ever have an ordering the pleases everyone and the benefits of making a change are minimal at best. Thanks anyway for the suggestion, @chenrujun.
