### ISSUE TITLE
V2_1 serviceCapabilities will create bootVersions ending in `.RELEASE`

### ISSUE THREAD

**Issue by gklijs** [spring-io/initializr#1373]
In the current main branch, when the endpoint is called, that returns `dependenciesFor(InitializrMetadataVersion.V2_1, bootVersion)` for example when no accept header is set or if `application/vnd.initializr.v2.1+json` is set as accept header, the bootversions will be returned with an additional `.RELEASE`. This will end up as the parent version, creation a project which can't be run without fixing the version.

**Comment by wilkinsona** [comment]
Thanks for the report, @gklijs. Unfortunately, I'm not sure that I understand the problem.

As far as I can tell, what you have described is the expected behavior. Support for SemVer-compliant versions was introduced in v2.2 of the metadata and it would be a breaking change if a request for an earlier version of the metadata received versions in that format. For this reason, and [as noted in the javadoc of `InitializrMetadataV22JsonMapper`](https://github.com/spring-io/initializr/blob/b527d1d9a6e54d7af51eaa7ebadfcf684afb7b61/initializr-web/src/main/java/io/spring/initializr/web/mapper/InitializrMetadataV22JsonMapper.java#L25-L26) early metadata versions use the old version format.

I suspect I may have missed something. Can you please expand a bit on the behavior that you're seeing and why you believe it to be incorrect?

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by gklijs** [comment]
Thanks for looking into it. It indeed seems to work as expected.
