### ISSUE TITLE
Spring boot starters bring in an insane amount of dependencies

### ISSUE THREAD

**Issue by palexdev** [spring-io/initializr#1405]
Hello, I'm developing a small desktop application, and I've chosen Spring Boot as my DI framework. While I was traveling back home this evening, I wanted to continue coding a little more from my tablet, but I couldn't because initializing the project took so much time (and still hadn't finished) that I arrived at my destination and I had to close everything.

Now, anecdote aside, what this made me realize was the insane amount of unneeded dependencies my Gradle setup was bringing in. For instance, I used Spring Initializr to generate the config, here it is:
```groovy
plugins {
    id 'application'
    id 'java'
    /*
    id 'org.springframework.boot' version "$springBoot"
    id 'io.spring.dependency-management' version "$springDM"
    */
    id 'org.openjfx.javafxplugin' version "$jfxPlugin"
}

dependencies {
    // Spring
    /*
    implementation ("org.springframework.boot:spring-boot-starter:$springBoot") {
        exclude group: "org.yaml"
        exclude group: "org.springframework.boot", module: "spring-boot-starter-logging"
        exclude group: "org.springframework", module: "spring-jcl"
    }
    testImplementation ("org.springframework.boot:spring-boot-starter-test:$springBoot") {
        exclude group: "com.jayway.jsonpath"
        exclude group: "jakarta.xml.bind"
        exclude group: "org.assertj"
        exclude group: "org.hamcrest"
        exclude group: "org.mockito"
        exclude group: "jsonassert"
        exclude group: "org.xmlunit"
        exclude group: "org.springframework.boot", module: "spring-boot-starter"
    */
    implementation ("org.springframework.boot:spring-boot:$springBoot") {
        exclude group: "org.springframework", module: "spring-jcl"
    }
    testImplementation ("org.springframework.boot:spring-boot-test:$springBoot") {
        exclude group: "org.springframework", module: "spring-jcl"
    }
}
```
As you can see, I was using the plugins, but then commented out them and started tinkering with the config.
Here's the list of things the initial config was importing, and I think I didn't need them:
- Logback
- jsonpath
- vaadin json (?)
- Jakarta activation
- Jakarta annotations
- Jakarta xml bind
- byte buddy
- accessors smart
- json smart
- Log4j
- slf4j
- assert4j
- hamcrest
- mockito
- objenesis
- asm
- jsonassert
- xmlunit
- snakeyaml (which is also considered a security risk by the IDE btw)

Just some numbers, with the default config I have a total (not only Spring) of 62 dependencies, with the custom configuration I have only 31! Half!

This is insane, what if one doesn't need all this stuff.
Shouldn't the Initializr be improved to provide a more lightweight configuration, or at least mention somewhere how to configure a project given one person's needs?

**Comment by wilkinsona** [comment]
Thanks for the feedback.

This isn't really an Initializr or start.spring.io issue, it's a feature of how Spring Boot's starters work. Their goal is to provide a set of dependencies that are a reasonable fit for most people's needs. Given that this is the first time we've received feedback like yours, I'd venture that we've succeeded in meeting that goal.

Looking at your exclusions, your needs appear to be quite specialised. For example, you appear to have excluded all, or close to all, of the logging related dependencies. We see very few, if any, applications that do not want to perform any logging. On the test side, you've excluded Hamcrest, Mockito, and AssertJ all of which are, in our experience, used more often that not in unit tests.

Given your apparent needs, I think you may be better off not using the starters and instead declaring more focussed dependencies directly. If you're just looking for a DI Framework, you may also want to consider using only Spring Framework rather than Spring Boot which builds on top of it.
