### ISSUE TITLE
Stop using dependency-management plugin

### ISSUE THREAD

**Issue by porterwoodward** [spring-io/initializr#1414]
The dependency management plugin was created prior to Gradle's support for BOM POMs.  Please consider not using it and just using:

`implementation platform('org.springframework.boot:spring-boot-dependencies:3.0.6')`

The dependency management plugin causes more problems than it solves now - and makes working around it within Gradle a bit of a pain when you need to override or exclude common dependencies like Jackson in order to address OWASP CVEs and the like.

**Comment by wilkinsona** [comment]
Thanks for the suggestion. We've thought about this several times since Gradle's platform support was introduced. As the primary maintainer of the dependency management plugin, I'd love the need for it to go away but I'm not sure that we're there yet.

IMO, and from what I've seen in feedback from users, the main remaining benefit of the dependency management plugin over Gradle's platform support is that you can use a property to override Spring Boot's dependency management. This is particularly powerful when the project whose version you want to override doesn't publish a bom as it makes the override significantly more concise.

> when you need to override … common dependencies like Jackson

This should be a one-liner with the dependency management plugin. Something like this:

```
ext { set("jackson.version", "2.15.0") }
```

Spring Boot [documents all of these version properties](https://docs.spring.io/spring-boot/docs/current/reference/html/dependency-versions.html#appendix.dependency-versions.properties), allowing the version of any third-party library that Boot manages to be overridden in the same way.

> or exclude common dependencies like Jackson

The dependency management plugin shouldn't affect how dependencies can be excluded. If it is then I would consider that to be a bug. Can you provide an example of it being a bit of a pain in this area?
