### ISSUE TITLE
Include junit-platform-launcher in Gradle builds

### ISSUE THREAD

**Issue by cschuyle** [spring-io/initializr#1476]
On October 19, 2023 , I went to https://start.spring.io, selected the defaults (Gradle-Groovy, Java, Spring Boot 3.1.5, Jar, Java 17), added a Spring Web dependency, and compiled the resulting project.  Here is the result:

```console 
➜  demo gw build
Starting a Gradle Daemon (subsequent builds will be faster)
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.3/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD SUCCESSFUL in 25s
7 actionable tasks: 7 executed
➜  demo gw clean build --warning-mode all
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended

> Task :test
The automatic loading of test framework implementation dependencies has been deprecated. This is scheduled to be removed in Gradle 9.0. Declare the desired test framework directly on the test suite or explicitly declare the test framework implementation dependencies on the test's runtime classpath. Consult the upgrading guide for further information: https://docs.gradle.org/8.3/userguide/upgrading_version_8.html#test_framework_implementation_dependencies

BUILD SUCCESSFUL in 2s
8 actionable tasks: 8 executed
```

The problem is that starting with Gradle 9, the resulting project will no longer compile.

So I followed the directions from the above snippet: I went to the link given, and added the following dependency to `build.gradle`:

```groovy
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher' // See https://docs.gradle.org/8.3/userguide/upgrading_version_8.html#test_framework_implementation_dependencies
```

This removes the deprecation warning, but I don't know:
- Is this a good fix?
- Is Spring Initializr the right place to make a fix?
- Are there other Spring projects involved?

**Comment by wilkinsona** [comment]
> Is this a good fix?

Yes, I think it is. An alternative would be to use test suites but I find their version management rather awkward. 

> Is Spring Initializr the right place to make a fix?

An alternative would be `spring-boot-starter-test`. We could declare a `testRuntimeOnly` dependency in the starter's `.module` file so that it would only affect projects being built with Gradle. An advantage of making the change in `spring-boot-starter-test` is that it would benefit everyone upgrading to Gradle 9, not just those creating a new project using start.spring.io. A potential disadvantage is that I'm not sure if it would play nicely with test suites for those that choose to use them. I'm also not sure what impact the change may have for projects built with earlier version of Gradle.

> Are there other Spring projects involved?

If we took the `spring-boot-starter-test` approach, Spring Boot would be involved. That change would probably remove the need for any changes to Initializr.
