### ISSUE TITLE
The first request to generate a gradle type project takes a very long time

### ISSUE THREAD

**Issue by devysf** [spring-io/initializr#1500]
The first request to generate a gradle type project takes a very long time. (Almost more than 10 seconds). There is no problem with requests after the first request. And this situation does not occur in maven.

You can test the project locally by running it and sending the first request. Since the first request has already been made in the production environment, the problem is not noticed.
<img width="1718" alt="image" src="https://github.com/spring-io/start.spring.io/assets/40598633/ffbe4906-c151-40bc-b374-90f5d5985e3c">

Actually, it is not very important in terms of usage, but integration tests for Gradle take too long.

**Comment by wilkinsona** [comment]
It's slower due to [this call](https://github.com/spring-io/initializr/blob/5143dcca46922e65284c93c917897fa4a032dfb2/initializr-generator-spring/src/main/java/io/spring/initializr/generator/spring/build/gradle/SpringBootPluginBuildCustomizer.java#L54) to `resolveDependencyManagementPluginVersion`. On start.spring.io, the version resolver retrieves versions lazily and they're then cached. On first request, there's a cache miss so it takes a little longer. If this is a problem for your use of the library, you can plug in your own resolver implementation with a different strategy.
