### ISSUE TITLE
add support for Lombok

### ISSUE THREAD

**Issue by chrylis** [spring-io/initializr#154]
In one-off projects where I'm not including all of Groovy, I prefer to use Lombok to clean up my objects. It'd be helpful to have it as one of the checkbox dependencies; even though it's not a Spring component itself, it's used widely enough (particularly in Spring tutorials and the like) that it seems including it would be appropriate.

**Comment by dsyer** [comment]
Lombok is already available if you choose anything from Spring Cloud. Without Cloud there is no Lombok version in the parent POM so I don't think the metadata supports adding it (it would have to be a different version depending on whether Cloud was included or not).

**Comment by snicoll** [comment]
For the record I was -0.5 for that change. Unless someones shows me how to draw a line between the third party libs that we can add and those we don't we could end up with a bunch of them. The only exception to the rules so far were jdbc drivers and that was fine enough for me.

Until we draw that line, I don't think it's a good idea to add third party libs (i.e. non starter) just because someone asks. If we can move on with that, that'd be great.

I have already rejected hazelcast twice so this is not fair to the guys who asked.

**Comment by chrylis** [comment]
The distinction that I think I have in my mind is between "libraries" and "build/language components", things I could just `@Grab` and infrastructure parts. Hazelcast, for example, might make sense to include *as a starter*, but there's nothing to "start" for Lombok (it doesn't even usually need runtime inclusion). I understand the rationale for limiting included options, but Lombok seemed to me close enough to the Groovy options to be worth suggesting.

If the decision is still not to include it, would it be worth considering having "hidden" searchable results that didn't go on the Big List O' Checkboxes but were still available for commonly-used components?

**Comment by dsyer** [comment]
I agree. Lombok is not in the same category as Hazelcast. Lombok is also included with Spring Boot 1.3 choices in the start.spring.io as well, so we can probably just close this?

**Comment by snicoll** [comment]
I  disagree. Either we have a dependency management for lombok in Boot itself or we don't add it. I see no reason why we should link that to Spring Cloud.
