### ISSUE TITLE
Add activiti starter

### ISSUE THREAD

**Issue by snicoll** [spring-io/initializr#155]
Originally raised in https://github.com/spring-projects/spring-boot/issues/1140

@jbarrez what is the reason for having so many starters? I'd like to add one starter for Activiti and let the user add extra dependencies if he wants to have additional features. Can you provide the main one and a description please? or a PR :)

**Comment by vpavic** [comment]
I like this proposal :+1:

Although I agree there are too many Activiti starters (since some of them are redundant due to similar starters from Spring Boot), due to Activiti's highly modular architecture IMO there are valid use cases for 3 of them:
* ```activiti-spring-boot-starter-basic```
* ```activiti-spring-boot-starter-rest-api```
* ```activiti-spring-boot-starter-actuator```

This [blog post](https://spring.io/blog/2015/03/08/getting-started-with-activiti-and-spring-boot) provides some insight.

Also ping @joshlong

**Comment by jbarrez** [comment]
Someone pointed this issue out to me - I seem to have missed it in my email traffic. @snicoll, apologies for the delay.

The reason for the many starters are indeed the different use cases for Activiti: standalone, in a webapp, with or without JPA, etc. Activiti has (optional) integrations with many things.and these starters allow to have autoconfigurations for these different setups.

Let me have a think about it and catch up with @joshlong about this so we can craft a PR and discuss further.
