### ISSUE TITLE
java.net.UnknownHostException

### ISSUE THREAD

**Issue by yerzhant** [spring-io/initializr#1557]
If you try to launch [this](https://start.spring.io/#!type=gradle-project-kotlin&language=kotlin&platformVersion=3.3.2&packaging=jar&jvmVersion=21&groupId=com.example&artifactId=demo&name=demo&description=Demo%20project%20for%20Spring%20Boot&packageName=com.example.demo&dependencies=postgresql,data-jdbc,native,security,devtools,configuration-processor,docker-compose,web,flyway,validation,testcontainers,cloud-feign), then everything is ok. But if you change image in compose.yaml to postgis/postgis then the app doesn't launch w/ error:
```
Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.

Reason: Failed to determine a suitable driver class


Action:

Consider the following:
	If you want an embedded database (H2, HSQL or Derby), please put it on the classpath.
	If you have database settings to be loaded from a particular profile you may need to activate it (no profiles are currently active).
```

**Comment by yerzhant** [comment]
I believe the issue must be opened in corresponding library but I didn't find the one. Sorry!

**Comment by mhalbritter** [comment]
The reason is that Spring Boot supports `postgres`, but not `postgis/postgis`. If you want to have support, please open an issue on [the Spring boot tracker](https://github.com/spring-projects/spring-boot/issues).

As a workaround, you can add a label to your docker compose container, as [documented here](https://docs.spring.io/spring-boot/reference/features/dev-services.html#features.dev-services.docker-compose.custom-images).
