### ISSUE TITLE
As a user I want to select the container to use

### ISSUE THREAD

**Issue by mdeinum** [spring-io/initializr#201]
Currently te applications generated always use Tomcat. However as a user I might want to select the container I want to use. Tomcat should then be (globally for gradle?) excluded and the correct starter for that container added.

**Comment by snicoll** [comment]
PR more than welcome. 

The main reason why it was not implemented is because dependencies are marked as `hierarchical-multi-select` and I'd rather have an overhaul of the input that implement something half-baked. 

We can't add a dependency group with the containers because you can select as many as you want there. And that does not make sense.

We can't add an option alongside Java & Boot version because a container only apply for a web application. That wold make things inconsistent and I feel that form is already large enough.

If you have an idea to implement that consistently, please let us know.

**Comment by mdeinum** [comment]
I haven't actually looked into an implementation (or how the recent versions of Initializr are implemented) but I can imagine it is a pain to setup especially with maven and gradle support. 

I actually imagined something alongside the java/boot version (maybe with a default for default or detect ). I'll ponder a bit more on the functional part and see how it could be implemented. I'm a bit swamped in work right now, so it might take some time.

**Comment by snicoll** [comment]
The actual build file generation is close to trivial compared to designing it properly in the UI and the meta-data. I already rejected the option alongside the java/boot version (see my comment).

**Comment by snicoll** [comment]
It's been a while and this one hasn't gained much traction.The simple form that we have is quite successful: we've made sure to avoid complex workflows and surely this one does not belong in the project metadata category.

I am happy to review a PR that would provide a sensible way to implement this though
