### ISSUE TITLE
Annotate Application class with provided @Enable... annotations

### ISSUE THREAD

**Issue by jkubrynski** [spring-io/initializr#203]
For example when I add dependency to `eureka-server` my Application class should be annotated by `@EnableEurekaServer`, etc.

**Comment by snicoll** [comment]
There's so much we can do. I agree it's a neat idea, PR welcome (though if anyone considers doing it we should have a larger conversation first as there are other related features that would benefit from such change).

**Comment by ryangardner** [comment]
> though if anyone considers doing it we should have a larger conversation first as there are other related features that would benefit from such change

Where should the conversation happen? This feature is something we could benefit from for an internal fork we are working on that will sit on top of the initializr but also add on some of our in-house tooling etc to it. 

Right now the initializr templates don't seem to have a lot of specific knowledge about the individual modules. To implement this properly you need to know what the modules need to add to the configuration of the application, and then get the generator to take advantage of this knowledge.

You could hard code in the knowledge in the templates - this is probably the easiest to implement
- Add conditional statements to the templates for each kind of ```@Enable``` kind of annotation that needs to be added to the application class

The downside is that every time you add a new module that makes different changes to the template, you also have to re-release the initializr application (they become more tightly coupled) currently it seems that you can simply add new modules by updating the yml config file and the initializr can add them without any additional tweaks. 

If you want to make it possible for the generator to not need to know about all of the modules and their custom things, it will need to dynamically be able to figure out what to put into the template from it. A few ideas come to mind: 
- Augment the information in the metadata to allow for additional stuff that gets put into the template. If you only want to support adding on "@Enable" style annotations, you could just add a field that would carry the additional annotation to add
- Add the ability to put inline templates into the metadata itself that the generator will execute when it runs. (Either have the metadata include the template directly or provide a URL to retrieve the template, whichever makes the most sense)

I think you want to walk a fine line here and not turn the initializr into some kind of full blown codegen machine - but focus on identifying a few places where hooks make sense to let modules add some template-based generation and strive keep it so that the generator is as ignorant of the modules as possible so that it is easy to add new modules.

I would favor doing something to allow the templates to specify additional templates in the metadata -  as that would lend itself to re-using the initializr and extending it by changing the metadata alone. We might be able to do this work and contribute it back through a PR if it sounded like a direction you thought would be worthwhile

**Comment by snicoll** [comment]
We actually had a meeting this week on this very topic. I am happy to share the details of the meeting and you can join gitter if you want to discuss this further. What we're trying to do is separate the current API in two separate stages:

1. Something that looks like `ProjectRequest` with a hook-point that would allow you to tune it based on its state (if dependency X is selected and no dependency of type Y is added, add dependency Z).
2. Based on that, a more rich model is created and another hook point allows to enrich the model. One thing that this model would include is a higher-level view of a source file. Something where you could invoke something like `addClassAnnotation(String annotationType)`

The first action is to create this new API, have proper name for it, etc. We're thinking of using a code source generator since we support 3 programming languages now but that's probably not going to happen short term unless someone contributes a PR for that. 

Regarding the hook-points, the idea is to create a bean of a certain type and we call you. Hook points can be ordered and a base implementation would solve the most common use cases. I don't think that adding that stuff to the configuration (yml) is going to work.

If you have some ideas or are willing to contribute a PR let us know.

**Comment by snicoll** [comment]
Duplicates #340
