### ISSUE TITLE
add camunda-bpm-spring-boot-starter to initializr

### ISSUE THREAD

**Issue by jangalinski** [spring-io/initializr#218]
We offer spring boot starters for the well known open source process engine/framework camunda.

We were discussing if it is possible to add this to the initializr, so users can start there camunda-spring applications easily. See https://github.com/camunda/camunda-bpm-spring-boot-starter/issues/52

Are you open for external contributions? Is there any documentation on how to provide the PR?

**Comment by snicoll** [comment]
Thanks for your interest in adding your starter to start.spring.io. [Deciding which starters to include](https://github.com/spring-io/initializr/wiki/Guidelines-for-3rd-Party-Starters) is a difficult balancing act as we want to cater to a broad audience while also not overwhelming people with too much choice. To help to strike that balance we like to be sure that a starter is widely used and will be of interest to a broad set of Spring Boot users. I’m not sure that the Camunda starter meets those criteria at the moment. Rather than adding it to start.spring.io now, may I suggest that you open a pull request to [add it to Spring Boot’s list of third-party starters](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-starters/README.adoc) instead?

**Comment by jangalinski** [comment]
Thanks for the info ... we will go on with the 3rd party site.
