### ISSUE TITLE
Consider adding Spring Twintip

### ISSUE THREAD

**Issue by AlexanderYastrebov** [spring-io/initializr#262]
https://github.com/zalando-stups/twintip-spring-web

**Comment by snicoll** [comment]
Thanks for your interest in adding your starter to start.spring.io. [Deciding which starters to include](https://github.com/spring-io/initializr/wiki/Guidelines-for-3rd-Party-Starters) is a difficult balancing act as we want to cater to a broad audience while also not overwhelming people with too much choice. To help to strike that balance we like to be sure that a starter is widely used and will be of interest to a broad set of Spring Boot users. I’m not sure that the TWINTIP starter meets those criteria at the moment. Rather than adding it to start.spring.io now, may I suggest that you open a pull request to [add it to Spring Boot’s list of third-party starters](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-starters/README.adoc) instead?
