### ISSUE TITLE
find a problem in fat jar that is spring-boot-starter-jersey

### ISSUE THREAD

**Issue by vincent-ren** [spring-io/initializr#315]
I send a problem to engineers.I have build a project use spring boot and jersey, i download this project at http://start.spring.io/ ,use this project start by SpringBootApplication main  is ok, but when i add this project in my tomcat, it have a strange error that make project can not run.  I find this problem take a full day. I find a fat jar has problem, this fat jar`s artifactId is spring-boot-starter-jersey, i must exclusions jersey-bean-validation and jersey-spring3, and add jersey-spring3 that version is 2.22.1, then this project has run. I am very hungry to know your reply. I will focus this issue. Thank you!

**Comment by snicoll** [comment]
@vincent-ren this is not the place to report such issue. Spring Initializr generates Spring Boot project but any potential issue must be reported in the [Spring Boot project](https://github.com/spring-projects/spring-boot) itself. When you do, please provide more details and the sample project that you've used because I am not sure I'd be able to reproduce the problem with your current description of it.

**Comment by vincent-ren** [comment]
oh,if you want get the sample project, please give me you email. Thank you very much!
