### ISSUE TITLE
Remove Zipkin Http Server

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-io/initializr#374]
The Zipkin server users should be using this https://github.com/openzipkin/zipkin#quick-start instead of the server generated by start.spring.io

cc @adriancole, @dsyer , @joshlong

**Comment by adriancole** [comment]
thx!

**Comment by eitansuez** [comment]
i'm curious to know: why should one be using the openzipkin project exclusively and not be able to create a spring boot app with the zipkin-server dependency (like we can so many other spring cloud projects: eureka, turbine, hystrix-dashboard, etc..)?

**Comment by adriancole** [comment]
Zipkin chose to use spring boot to write its server but in doing so did not
intend to support people who cannot start exclipse or figure out what
classpath conflicts are. The default server already does what most have
been trying to accomplish, so taking it off here removes the temptation and
the burden.

Think of zipkin like ElasticSearch or Cassandra. Most people can use these
projects with no experience as it is built to be used as it was built.
Advanced users can and do build custom servers but we dont want to
advertize this as step one (here).


On 6 May 2017 4:12 am, "Eitan Suez" <notifications@github.com> wrote:

i'm curious to know: why should one be using the openzipkin project
exclusively and not be able to create a spring boot app with the
zipkin-server dependency (like we can so many other spring cloud projects:
eureka, turbine, hystrix-dashboard, etc..)?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/spring-io/initializr/issues/374#issuecomment-299564354>,
or mute the thread

**Comment by eitansuez** [comment]
thanks!
