### ISSUE TITLE
Add Keycloak Spring Boot Adapter to Starter's page

### ISSUE THREAD

**Issue by sebastienblanc** [spring-io/initializr#376]
Hi,

We have a Spring Boot Adapter for Keycloak (http://www.keycloak.org/) which is already pretty popular in the community.

Regarding the guidelines, You can see my comments here : https://gist.github.com/sebastienblanc/b3d3c8762d3f4feba00b661885a91b93

Code source of the Adapter is here : https://github.com/keycloak/keycloak/tree/master/adapters/oidc/spring-boot

Documentation is here : 
https://keycloak.gitbooks.io/securing-client-applications-guide/content/topics/oidc/java/spring-boot-adapter.html

We have also a starter : 
https://github.com/keycloak/keycloak/tree/master/misc/spring-boot-starter

and a BOM : 
https://github.com/keycloak/keycloak/blob/master/boms/adapter/pom.xml

Regards,

**Comment by sebastienblanc** [comment]
Hi ! 
Is there is any additional info needed ?
Sebi

**Comment by snicoll** [comment]
I don't know yet. I haven't had a chance to look at it.

**Comment by snicoll** [comment]
I had a look at the code and there are a few things we'd like you to reconsider before going further with this request: 

We need the necessary tests for the Spring Boot integration (there are none as far as I can see)

We don't want to add an extra lib for the servlet container adapter and we would like you to consider bundling that somehow with the starter. Not doing so means that:

* We have to chose the one that matches what "spring-boot-starter-web" brings
* We have to make sure that it matches the right version (we may want to bring a different tomcat version by default in Boot 2 for instance). That's a maintenance burden we're not keen to accept

None of your `@ConfigurationProperties` fields are documented and no metadata for the IDEs is generated. Please add documentation and the `spring-boot-configuration-processor` so that the IDE can show that in auto-completion.

The `version.keycloak` version in your bom doesn't look right to me. If you import a bom of version A.B.C it makes no sense to ask for D.E.F. (a dependency may have been added/remove in that version). I'd rather hard-code the version in each `dependency` (that will be updated by the release process the same way as the property anyway). Also, that bom is a child of your main pom which is usually a bad idea. I can see that you have a `repositories` definition there that is going to pollute the Maven build. Worse, you inherit from the dependency management of the whole infrastructure (including Jackson, log4j and a bunch of 3rd party libraries). We can't accept a bom that does that as it conflicts with Spring Boot's dependency management.

There are other remarks on the auto-configuration code itself that are less important. Let's see first if we can sort this out. Thanks!

**Comment by sebastienblanc** [comment]
Thanks for this useful feedback, it's all make sense to me except : 
`We don't want to add an extra lib for the servlet container adapter and we would like you to consider bundling that somehow with the starter.` 
Could you elaborate on that ? I'm not sure to understand , our starter bundles the Spring Boot Adapter and the Tomcat8 adapter ( https://github.com/keycloak/keycloak/blob/master/misc/spring-boot-starter/keycloak-default-spring-boot-starter/pom.xml ) and matches with what brings in `spring-boot-starter-web` (tomcat)

**Comment by snicoll** [comment]
Thanks for the feedback!

This alignement is fragile IMO. It works now but may very well broken quite quickly.

There is not a lot of code so what is the value of having all those modules vs. having the code and load the right implementation once you've detected in which environnement you are running on?

**Comment by sebastienblanc** [comment]
The tomcat/undertow/jetty adapters can (and are usually) used without Spring Boot but let me discuss with the team if we can just add these as dependencies directly in the Spring Boot Adapter.

**Comment by sebastienblanc** [comment]
Hi ! Here a small update on this task : 
* The BOMs has been refactored with your feedback : the versions are set in each dependency and the BOM no longer inherit from the main POM of the project (instead it inherits the JBoss Parent BOM that doesn't bring any other dependencyManagement or repositories).
* Config properties are now documented and `spring-boot-configuration-processor` has been added, offering now auto-completion for the IDEs

What is left : 
* Adding Integration's test for the adapter 
* Find a solution how to bundle tomcat/undertow/jetty adapters with the SB adapter. I haven't find a solution for this right now as we can not add the 3 of them as dependency in the Spring Boot Adapter, they will conflict with each other.
