### ISSUE TITLE
Restructure documentation to provide a configuration guide

### ISSUE THREAD

**Issue by snicoll** [spring-io/initializr#392]
The current documentation is a migration of what we used to have on the wiki. We need to structure it a bit more, offering a section that explains what the configuration features are. 

What I had in mind is something like this:

* `Introduction` - explains what Initializr is and all the core concepts. Also provides a bunch of link to other sections
* `User guide`- describes how to use the web interface and the command-line support
* `Configuration guide` - based on the user guide that should provide a good description of the user-facing features, explain how to configure an instance for various use cases. This is the heart of the documentation really
* `Developer guide` - describes the endpoint, the metadata format and how the stub can be used. This is a good resource for anyone willing to create a custom client.

The guide isn't as big as other projects so having "parts" for each of those might be a bit too much. I am not sure they should be named it like that either.

**Comment by dsyer** [comment]
That looks like a reasonable outline to start with. I would call the "Developer Guide" an "API Guide", since it is developers of other systems we are targeting, not developers of the Initializr.

I also wonder if there might be a separate section on how to extend the service, and/or use it as a library. This topic kind of goes beyond simple configuration, but it's quite common for people to want to do this. We don't have to do this right away of course.

**Comment by snicoll** [comment]
We already have a good chunck of this work on master already. It's not perfect but good enough for now.
