### ISSUE TITLE
Spring Session support broken post Spring Boot 2.0.0 M2

### ISSUE THREAD

**Issue by vpavic** [spring-io/initializr#455]
Due to recent changes in Spring Session which have been picked up by Boot in spring-projects/spring-boot@f26f817, Initializr generated projects that include Session will refer to non-existing `org.springframework.session:spring-session` artifact.

**Comment by snicoll** [comment]
Thanks for the heads up. I'll disable spring session for now and like some guidance as how to restore it. I really do not want one entry per store.

**Comment by snicoll** [comment]
There are things that should happen in Spring Boot to improve the developer experience with Spring Session the way it has been modularized. Regardless, we need to restore spring session ASAP on the production instance. I've made a proposal in the Spring Boot related issue (https://github.com/spring-projects/spring-boot/issues/9552#issuecomment-313625799) 

Any feedback on the proposal would be welcome so that we can move forward with this.

**Comment by snicoll** [comment]
We are close to 2 months with this with zero feedback.

**Comment by vpavic** [comment]
Having in mind the current constraints in Boot/Initializr the proposal does seem as the best way to address the current.

Obviously it isn't ideal that when user selects `session`, `jdbc` and `redis` they get both `spring-session-data-redis` and `spring-session-jdbc` but I assume there are plenty other situations where generated project requires user intervention. Other situation is when user selects `session` but no data store starter that results in `spring-session-core` which by itself does not contain a production grade `SessionRepository` implementation.
