### ISSUE TITLE
Support for adding custom code templates

### ISSUE THREAD

**Issue by dturanski** [spring-io/initializr#47]
I'm thinking of something similar to mvn archetype but better to generate a project from custom code templates.  mvn archetype supports code templates using velocity and simple placeholder substitution. Also dynamic directory paths that bind to properties, e.g. /src/main/resources/../**artifiact_id**/..   .I'm specifically looking at what can be leveraged for Spring XD modules.  In this case, there is no main (Application.java) , but some configuration templates - files generated for src/main/resources and corresponding tests.  Beyond what the maven archetype plugin does, some support for profiles or conditional configuration would be great, i.e., alternate source sets driven by a property value.  e.g.: moduleType = (job,source,processor,sink).   The output of a sample processor project would be based on https://github.com/dturanski/spring-xd/blob/java-config-module/spring-xd-module/src/test/resources/ModuleFactoryTests/modules/processor/siDslModule.zip[this]

**Comment by reneeWe** [comment]
I have the same issue as dturanski.
To respond the question of snicoll: yes, we'd like to deploy owr own instance of start.spring.io. We would like to be able to customize our own instance to offer users the possibility to generate a kind of template project structure, with specific classes, tests and resources. Additionally we would like to propose some libraries/starters as default, so that they are automatically selected, but the user has the possibility to uncheck it, if really not wished. 
The fork https://github.com/SchweizerischeBundesbahnen/initializr shows modifications done in the original initializr code to add the mentioned possibilities. A further stepp would be to allow the same result in a generic way, to allow customization without having to modificate the original code.

**Comment by snicoll** [comment]
I think it would help if you could come up with a proposal for each feature that you have implemented so far. We can decide then to either integrate those features or offer you a way to customize the  code without forking the library. This issue has a dedicated scope and I'd rather have the discussion in dedicated issue(s). Thanks!

**Comment by dturanski** [comment]
In my case, the original description is obsolete as we move to SCDF. However I think it would still be useful to have the ability to generate some type of working example. In the case of a SCDF module the configuration might include @EnableBindings, MessageChannels annotated with @Input and @Output and a some meaningful tests.

**Comment by snicoll** [comment]
Duplicates #340
