### ISSUE TITLE
Automatically configure the jpa Kotlin plugin if Kotlin is the language and JPA is a dependency

### ISSUE THREAD

**Issue by nfrankel** [spring-io/initializr#537]
I was pleasantly surprised to see the `allopen` plugin is automatically configured in the POM if you choose Kotlin as the language.

To go a bit further, it could be great to automatically configure the `noarg` plugins if you choose Kotlin and JPA is added as a dependency.

**Comment by snicoll** [comment]
paging @sdeleuze - What would be the downside to add this by default?

**Comment by sdeleuze** [comment]
I am all for adding the `jpa` plugin by default to Kotlin projects with JPA dependency since JPA requires default constructor per spec. `jpa` plugin is a pre-configured variant of the `noarg` plugin, similar to what the `spring` plugin is compared to the `allopen` one.

For projects without JPA dependency, IMO no need of `noarg` plugin, since it requires to target specific annotations and since most other databases supported by Spring Data Kay now supports Kotlin classes initialized by constructor.

**Comment by wilkinsona** [comment]
@sdeleuze Thanks. 

> I am all for adding the jpa plugin by default to Kotlin projects with JPA dependency

Right now, Initializr doesn't support adding a dependency if a particular language is being used and if another dependency has been added.

> For projects without JPA dependency, IMO no need of noarg plugin, since it requires to target specific annotations

We were wondering if we could implement this requirement sooner rather than later by simply adding the `noarg` plugin whenever Kotlin is used and irrespective of the use of JPA. Looks like the answer is no.

I'll retitle this issue to reflect the fact that the `jpa` plugin is the one to add, rather than `noarg`.

**Comment by snicoll** [comment]
Closing in favour of PR #728

**Comment by xmlking** [comment]
Please also add jpa Kotlin plugin if r2dbc-data added

**Comment by wilkinsona** [comment]
@xmlking Why would a project using R2DBC want to use Kotlin's JPA plugin? I am not aware of connection between the two. Can you please outline the benefits?

**Comment by xmlking** [comment]
@wilkinsona my problem has been explained here 
https://twitter.com/xmlking/status/1624663494531641345?s=61&t=NyxifCDot1_d66fXOxUvBg
its failing at unit tests without no-arg constructor

**Comment by xmlking** [comment]
B.t.w Kotlin's JPA plugin and Kotlin's noArg plugin are same. 
We need noArg contractor for for tests to work here 
https://github.com/xmlking/micro-apps/tree/main/services/spring-graphql-r2dbc

**Comment by wilkinsona** [comment]
Thanks for the additional details. Unlike JPA, Jackson doesn't always require a default constructor so it's not entirely clear to me what's causing the error shown in your Twitter thread. It's too soon to be making a change to Initializr because, as far as I know, a default constructor should not be required. I'd recommend asking a question on Stack Overflow, tagged with `spring-graphql`, to see if someone can help you to remove the need for the default constructor.

/cc @bclozel @rstoyanchev

**Comment by xmlking** [comment]
Thanks @wilkinsona bootRun work without noArg constructor but only test fails
