### ISSUE TITLE
when the project created，add new dependencies

### ISSUE THREAD

**Issue by cococa** [spring-io/initializr#544]
When the project  is created,   can add new dependencies with  the spring io initializr?
 I use intellij idea  and gradle .

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-io/initializr/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
