### ISSUE TITLE
Dependency-Check Results

### ISSUE THREAD

**Issue by FanyCastro** [spring-io/initializr#573]
Hello, 

I have check the vulnerabilities of my proyect and I have got these issues: 

https://nvd.nist.gov/vuln/detail/CVE-2017-15535
https://nvd.nist.gov/vuln/detail/CVE-2013-2132
https://nvd.nist.gov/vuln/detail/CVE-2012-6619

I am using the following versions of my dependencies: 

        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>**1.5.9.RELEASE**</version>

        <groupId>org.springframework.boot</groupId>
        <artifactId>**spring-boot-starter-data-mongodb**</artifactId>

Could you please let me know if these are false positives? Or if there are not, what could I do to fix this? 

Thank you very much in advance.
Best regards.

**Comment by snicoll** [comment]
> Could you please let me know if these are false positives? 

I  am afraid that's not the place to ask. This project  is not handling what Spring Boot does or the  dependencies that it brings. My experience is that either it is a false positive (because specific to a very narrowed environment) or not applicable to what Spring Boot  does by default or  via configuration. Either way, you can ask on StackOverflow.
