### ISSUE TITLE
Hibernate JAXB Dependency Missing

### ISSUE THREAD

**Issue by michaelhoffmantech** [spring-io/initializr#590]
I'm trying to create a demo project with Spring Initializr with JPA and I am running into an exception on startup: 

```
Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
        at org.hibernate.boot.spi.XmlMappingBinderAccess.<init>(XmlMappingBinderAccess.java:43) ~[hibernate-core-5.2.12.Final.jar:5.2.12.Final]
```

I used the following selections: 

- Gradle Project
- Java 9
- Spring Boot 2.0.0 RC1
- JAR
- Dependencies = DevTools  Actuator  Web  JPA  H2

The root cause is the removal of the JAXB APIs as part of Java 9 (https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j). I assume this is more of a Spring Boot issue with how dependencies are included, but perhaps JAXB can be added as a dependency module on the Initializr page as an option?

[demo.zip](https://github.com/spring-io/initializr/files/1693063/demo.zip)

**Comment by snicoll** [comment]
>  I assume this is more of a Spring Boot issue 

Not really. It's a change in Java9 so if you decide to use it you can either add the dependency yourself or include the module that is now optional. I've added https://github.com/spring-projects/spring-boot/issues/11205 to RC2 so that don't  have to specify a version for it.

> perhaps JAXB can be added as a dependency module on the Initializr page as an option

Sorry, no. The search picker is not meant to add whatever makes sense and is on Maven central.
