### ISSUE TITLE
Create the starter project in a self contained directory

### ISSUE THREAD

**Issue by rwinch** [spring-io/initializr#65]
To me it is surprising to download a file from start.spring.io and unzip it and have anything but a self contained directory.

For example, if I used start.spring.io I might unzip the result to ~/code/ which contains all of my other code in it. Then I would need to find all the contents of the zip, delete them, create a new directory, and extract it there.

If instead the zip contained a folder named demo (i.e. the name entered into the UI) then all the contents would be self contained.

**Comment by snicoll** [comment]
You have a point here. I guess it wasn't such an issue so far since MacOS creates a directory with the name of the zip file by default. This is tricky as changing this breaks the CLI: if you run `spring init -d=web foo-bar` then you get a new `foo-bar` directory with your web-based Spring boot project. 

If we create an extra directory in the archive, that use case is broken. It's a bit ambivalent: I really dislike when things are being extracted in the current directory but on the other hand if we "burn" a directory in the archive, there's no way for you to choose where to actually extract the project (i.e. if you want to extract in `~/code/foo-bar`, it stills create a `demo` directory in it). 

Thoughts?

**Comment by rwinch** [comment]
> on the other hand if we "burn" a directory in the archive, there's no way for you to choose where to actually extract the project (i.e. if you want to extract in ~/code/foo-bar, it stills create a demo directory in it).

True, but this is a lot easier to fix. If you extract the existing zip to a directory that contains lots of files, cleanup is a lot more difficult as you need to find all the files that need to be moved into a directory.

I do see your point about backward compatibility. Perhaps this needs to be a larger discussion.

**Comment by dsyer** [comment]
It only has to be a feature of the HTML UI i think. Seems like a good idea to me (an optional extra parameter that isn't exposed to the CLI client).

**Comment by snicoll** [comment]
@rwinch @dsyer I have pushed a candidate fix for this issue on http://start-staging.cfapps.io/ - Could you please try that out with your existing use cases to make sure it does what you want?

Thanks!

**Comment by dsyer** [comment]
It does. Thanks.

**Comment by rwinch** [comment]
Works for me. However, why not allow the parameter to be used in the CLI? Obviously you would not want to change the default behavior, but I think it would be valuable from a CLI tooling too.

**Comment by snicoll** [comment]
I'd prefer not adding too much parameter in there. We already have too much of them if you ask me.

**Comment by rwinch** [comment]
It just seems like it would simplify the steps for a lot of [instructions](https://spring.io/blog/2015/01/12/spring-and-angular-js-a-secure-single-page-application#using-curl) that have to do something like:

```bash
$ mkdir ui && cd ui
$ curl https://start.spring.io/starter.tgz -d style=web \
-d style=security -d name=ui | tar -xzvf - 
```

**Comment by snicoll** [comment]
```bash
$ curl https://start.spring.io/starter.tgz -d style=web \
-d style=security -d name=ui -d selfContaind=true | tar -xzvf - 
```

**Comment by rwinch** [comment]
I was not aware of that parameter. Thanks! Looks great to me :)

**Comment by snicoll** [comment]
that reminds me there is still an "inconsistency" between `name` and `artifactId`. That command above is going to create a directory named `demo` because `name` is the attribute for the "name" of the project, not the identifier of the _artifact_. We use `artifactId` to derive the name of the directory and the `artifactId` entry of the build; We use `name` to derive the name of the app and the name entry in the pom. 

The proper entry would be 

```bash
$  curl https://start-staging.cfapps.io/starter.tgz -d style=web \
-d style=security -d name=ui -d artifactId=ui -d selfContained=true | tar -xzvf - 
```

**Comment by snicoll** [comment]
@dsyer, @rwinch and I discussed offline and the  `selfContained` parameter is confusing. Rob is suggesting `useBaseDir`. Thoughts?

**Comment by dsyer** [comment]
I would prefer `-d baseDir=ui` , and default that to something sensible in the UI. I think you implemented it to default as the "artifact" ID (not the "name") BTW (at least that's what happens when I try it from start-staging.cfapps.io).

**Comment by snicoll** [comment]
@dsyer @rwinch staging has been updated with that suggestion. The new command is

```bash
$ curl https://start-staging.cfapps.io/starter.tgz -d style=web \
-d style=security -d name=ui -d baseDir=ui | tar -xzvf -
```

How does that sound?
