### ISSUE TITLE
spring initialzer plugin for idea

### ISSUE THREAD

**Issue by dingxuehua** [spring-io/initializr#716]
Is there an IDE plugin? Source code?

**Comment by snicoll** [comment]
Courtesy of Google translate

> Is there an IDE plugin? Source code?

Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-io/initializr/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
