### ISSUE TITLE
choosing Java 11 causes java.version to be set to 1.8 in pom.xml file

### ISSUE THREAD

**Issue by martinlippert** [spring-io/initializr#739]
I create a project and select Java 11 + maven, but the project gets `<java.version>1.8</java.version>` generated.

**Comment by kdvolder** [comment]
Just to add, it is the same for gradle projects too. Selecting Java 11 generates a build.gradle that has this line in it:

```
sourceCompatibility = 1.8
```

**Comment by wilkinsona** [comment]
What version of Boot did you use? You need to select Spring Boot 2.1 to use Java 11, otherwise the Java version is deliberately downloaded to 8 as Boot 2.0 and earlier do not support Java 11.

**Comment by martinlippert** [comment]
@wilkinsona haha, you are absolutely right, that is the piece that I stumbled upon.... Lets close this again.

**Comment by wilkinsona** [comment]
Yeah, our opinion is that the silent downgrade is the least bad option. A better one may be some metadata that describes the valid combinations so that it can be sorted out on the client-side. That wouldn't help users creating projects using curl though, and would require changes in the service and clients before it became useful.

**Comment by kdvolder** [comment]
Perhaps we should put some thought into these kinds of scenarios so that the initializer service might provide some kind of diagnostic feedback when user selects a 'invalid' combination of option. I think that would be preferable over just silently changing some of the options. Maybe the service could provide an endpoint to 'validate' a selection of options and it could return a some result indiicating 'this looks okay' or some sensible error message that the wizard could display to the user?

Just a thought. Not sure it is worth the effort to develop this.

**Comment by asarkar** [comment]
@wilkinsona I found this problem using `2.1.7.RELEASE`. See `build.gradle` below.
```
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
	id("org.springframework.boot") version "2.1.7.RELEASE"
	id("io.spring.dependency-management") version "1.0.8.RELEASE"
	kotlin("jvm") version "1.2.71"
	kotlin("plugin.spring") version "1.2.71"
}

group = "com.example"
version = "0.0.1-SNAPSHOT"
java.sourceCompatibility = JavaVersion.VERSION_1_8

repositories {
	mavenCentral()
}

dependencies {
	implementation("org.springframework.boot:spring-boot-starter-webflux")
	implementation("com.fasterxml.jackson.module:jackson-module-kotlin")
	implementation("org.jetbrains.kotlin:kotlin-reflect")
	implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
	testImplementation("org.springframework.boot:spring-boot-starter-test")
	testImplementation("io.projectreactor:reactor-test")
}

tasks.withType<KotlinCompile> {
	kotlinOptions {
		freeCompilerArgs = listOf("-Xjsr305=strict")
		jvmTarget = "1.8"
	}
}

```

**Comment by wilkinsona** [comment]
This is the expected behaviour when using Kotlin. Kotlin generates Java 8 byte code and doesn't make any use of Java 11's features (note the `stdlib-jdk8` dependency, for example). So, for consistency with that, the Java version is downgraded to match.

#211 and #773 are tracking some changes in this area which may be of interest.

**Comment by asarkar** [comment]
@wilkinsona I think some sort of indication would be very helpful. Either the Java 8+ options could be disabled, or a pop up with the explanation you provided...anything but crickets.

**Comment by wilkinsona** [comment]
I've opened https://github.com/spring-io/start.spring.io/issues/250 so that we can consider our options.
