### ISSUE TITLE
How to dynamic add a customer dependency？

### ISSUE THREAD

**Issue by wzlee** [spring-io/initializr#838]
We defined some dependency, and i want to generate a application with those dependencies.
I can add those dependencies to metadata's dependencies by consumer a metadatabuilder,
but when i defind new dependency, then i need to restart the web to load the dependency.
Is there any other way to dynamicly add a customer dependency？

**Comment by snicoll** [comment]
`master` has an `InitializrMetadataUpdateStrategy` that you can use [to "refresh" the metadata](https://github.com/spring-io/initializr/blob/4ed8089a35239d805c20fd6126b9a81fdaf0e07c/initializr-web/src/main/java/io/spring/initializr/web/support/InitializrMetadataUpdateStrategy.java#L35) once the cache entry expires.

The default implementation is contacting sagan to see if there are new versions of Spring Boot. You could wrap that and build whatever logic you have there. Keep in mind it's going to be called every time the cache expires so you need a way to know that something has been added since the last time this was called.

If you have more questions, please ask on StackOverflow or join us on Gitter: as mentioned in [the guidelines for contributing](https://github.com/spring-io/initializr/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements.
