### ISSUE TITLE
how to get stater groupid,artifactId,version

### ISSUE THREAD

**Issue by saturnLong** [spring-io/initializr#902]
hi,  i have a company initializr project  and  some customize stater. i want to use all spring  initializr  stater。 https://start.spring.io/ui/dependencies，this request has no response then groupid,artifactId,version.  how  to get these  infomations 。

thank you

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-io/initializr/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
