### ISSUE TITLE
Add support for removing build plugins

### ISSUE THREAD

**Issue by celcius112** [spring-io/initializr#909]
At the moment, unless I'm missing something, we cannot configure the plugins the initializr adds automatically. For instance, I would like to remove the `io.spring.dependency-management` plugin and replace the `org.springframework.boot` (yes that's sacrilegious) by another custom plugin that manages these plugins (I'm using Gradle). Similar case for the Java plugin.
I was wondering if the plugins could have the same configuration abilities as the `dependencies` or `repositories` fields found in the abstract class `Build`. With a `BuildCustomizer` with lowest precedence configuring the default plugins might be possible

**Comment by snicoll** [comment]
Right now we are targeting an arrangement where initializr-generator-spring represents our conventions and is a totally optional dependency so that you can rollout your own conventions if you disagree.

This seems to be a bit nuclear to have to do that to remove a plugin so I am tempted to offer such capability and reusing the `BuildItemContainer` sounds interesting as long as we have an obvious way to reference a plugin by id.

Flagging for team attention to see what the rest of the team thinks.

**Comment by snicoll** [comment]
Closing in favour of PR #978
