### ISSUE TITLE
Add all available dependencies properties in application.properties

### ISSUE THREAD

**Issue by akuma8** [spring-io/initializr#918]
I don't know the level of difficulty of this request but I wonder if it's possible, when starting a new project from the initializr to add all available properties in `application.properties` and comment them. Those properties would be based on choosen dependencies.
Thanks

**Comment by wilkinsona** [comment]
Thanks for the suggestion, but I'd rather address this via Spring Boot's documentation so that information about the properties is available to everyone, not just users of start.spring.io.

You may already be aware of the appendix in Spring Boot's documentation that lists all the properties. We've modified that in 2.2 to divide things up a bit as you can see [here](https://docs.spring.io/spring-boot/docs/2.2.0.M3/reference/html/appendix.html#common-application-properties). We [plan to do more](https://github.com/spring-projects/spring-boot/issues/16267) before 2.2 is released.
