### ISSUE TITLE
Add option for config in yaml

### ISSUE THREAD

**Issue by ctl80** [spring-io/initializr#94]
Currently this produces a /src/main/resources/application.properties for configuration.

Please add an option to produce /src/main/resources/application.yaml instead, with properly formatted contents too of course.

**Comment by dsyer** [comment]
There are no contents in the `application.properties` so it's pretty easy to rename it to `application.yml` and it's still valid (i.e. I might prefer to leave this up to the user - too many choices in the app get a bit confusing). I could certainly get behind defaulting to `.yml` instead of `.properties`.

**Comment by snicoll** [comment]
I most certainly agree of restricting the options to a core set. As from yml, I am kinda in the opposite camp but I am sure you know that already.

**Comment by snicoll** [comment]
Closing this one for now. We can reconsider using yaml as default once the IDE support is better in that area.

**Comment by gregturn** [comment]
@snicoll now that IDE support for YAML files is in place (at least it is in IntellIJ) can we entertain flipping the default?

**Comment by snicoll** [comment]
I am afraid not. The YAML support is certainly not at the same level as the one for properties (at least in IJ)
