### ISSUE TITLE
Invalid cache strategy for metadata lookup

### ISSUE THREAD

**Issue by snicoll** [spring-io/initializr#979]
There has been several cases where a refresh of the metadata is not taken into account by the web client. 

Cloudflare seems related as the update works in certain region and not in other. We've pushed a workaround in spring-io/start.spring.io#213 we should probably revert in benefit of a proper cache strategy for the metadata, forcing refresh on the server side.

**Comment by bclozel** [comment]
I think we need to reduce the cache duration for the metadata endpoint, here: https://github.com/spring-io/initializr/blob/f33a6610747c5b042c83d07e7c36265b3d29c56e/initializr-web/src/main/java/io/spring/initializr/web/project/MainController.java#L196

**Comment by snicoll** [comment]
I was wondering if we couldn't keep a last modifier date in the metadata and then use that as a relative value for the cache? We can make a compromise and store the instant in `InitializrMetadata` somewhere and move that information somewhere else once that part of the code base has been refactored. Thoughts?

**Comment by bclozel** [comment]
[According to the `Cache-Control` HTTP headers behavior](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/http-caching#max-age), I think we were too agressive with that `max-age` value.

Browsers should behave like this:
1. download the resource if the cache is empty
2. when visiting the website again:
2.1 if the `max-age` duration is not expired, reuse the resource directly
2.2 if the `max-age` duration is expired, ask the server if the resource is still valid using the `ETag` value we've sent. If there's a new resource, the server is replying with it, otherwise the server tells the client that the cached version is still valid

Since we're using a CDN, those checks are really cheap. Ultimately, we've got to answer the following: "How long do we think it's acceptable for a client to reuse the metadata without checking if a new version is out?".

In my opinion, developers might generate a few projects within minutes, but checking every other hour should be a good compromise. What do you think?

**Comment by snicoll** [comment]
Thanks for the feedback. My main concern is when we release a new version and we update the metadata to point to the new version. This potential window where we'd show the old version is the critical aspect of it. And quite frustrating since the metadata is immutable the rest of the time really. If that's the only option we need to figure how an acceptable windows for the upgrade use case.

**Comment by vianneyfaivre** [comment]
Could you make that value configurable? Plus, if it's empty, don't send the Cache-Control header at all? Or drop that header and assume that people will configure caching in another layer (api gateway, nginx, ...)?

We have done the same kind of workaround in our frontend to avoid having the version cached for a week.
