### ISSUE TITLE
Allow to invoke project generation with a custom ProjectRequest

### ISSUE THREAD

**Issue by jpasquali** [spring-io/initializr#990]
Spring Initializr provides a RESTful API for generating a project.
I would like to use this to add additional fields into the ProjectRequest. Today I can extend the MainController 
and define my own implementation of the ProjectRequest object in the MainController#projectRequest method.
However, Spring Initializr does not allow me to provide my own implementation of the ResolvedProjectDescription, which is added into the ProjectGenerationContext and could be used in the Contributors.
To be able to use my extension / additional fields in the Contributors, it would be good, if I could add my object to the ProjectGenerationContext.

Meaning it would be nice, if the Initializr could provide a hook for this, without the need to overwrite the ProjectGenerationInvoker.

E.g. the ProjectGenerationInvoker#invokeProjectStructureGeneration method could provide a java.util.function.Consumer<ProjectGenerationContext> as parameter.
The Maincontroller could provide a protected method, which I could overwrite to add my own consumer.

There might be better solutions for the hook, but I hope it explains what I would like to do.

**Comment by snicoll** [comment]
Thanks for the report. I've been working on #993 to reduce the number of things to change to get a custom `ProjectDescription` in the generation context. I'd like to rework `MainController` so that it doesn't have so much responsibilities (see #994).

Once those two are done, I'd like to explore how adding a custom `ProjectRequest` (and therefore a custom `ProjectDescription`) can be implemented in a custom instance.
